version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  vispr:
    ports:
      - "5000:5000" # not sure if necessary
    image: python:3.9
    restart: unless-stopped
    working_dir: /code
    volumes:
      - /home/vispr/sars:/data
      - /home/vispr/covid19-screens/vispr/:/code
    command: "/bin/bash -c 'python setup.py install && vispr server --host 0.0.0.0 --port 5000 /data/*/workflow/results/*.yaml'"
    hostname: vispr

